FROM node:22-alpine

WORKDIR /inkeep-agents

RUN npm install -g pnpm@10.17.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY turbo.json drizzle.config.ts ./

RUN pnpm fetch

COPY scripts/ ./scripts/
COPY apps/shared/ ./apps/shared/
COPY apps/manage-ui/ ./apps/manage-ui/

RUN pnpm install --frozen-lockfile --offline

ENV SKIP_APP_INSTALL="1"

RUN pnpm inkeep dev --export --output-dir ./apps/manage-ui

WORKDIR /inkeep-agents/apps/manage-ui

RUN pnpm install --no-frozen-lockfile --ignore-scripts

RUN pnpm next build

EXPOSE 3000

CMD ["pnpm", "next", "start"]
