FROM node:22-alpine

WORKDIR /inkeep-agents

RUN npm install -g pnpm@10.17.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY turbo.json drizzle.config.ts ./

RUN pnpm fetch

COPY apps/ ./apps/
COPY scripts/ ./scripts/

RUN pnpm install --frozen-lockfile --offline

CMD pnpm db:migrate
